version: '3.9'

services:
  api1: &api1
    hostname: api1
    build:
      context: ./RinhaBackend
      dockerfile: Dockerfile
    depends_on: 
      - db
    environment:
      PORT: 8080
    ports:
      - "8081:8080"
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "200MB"

  db:
    image: postgres:latest
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rinha
    ports:
      - "5432:5432"
    command: postgres -c max_connections=300
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "130MB"